declare module 'escape-string-regexp';
declare module 'ect';
declare module 'powerdash';
declare module 'lodash';
declare module 'run-sandboxed';
declare module 'find-derived';
declare module 'arr-flatten';
declare module 'mkdirp-promise';
declare module 'node-dirutils';
